### DISCUSSION TITLE
PostgreSQL Connector Issue: Unable to create replication slot while runnning Dozer (ERROR Failed to create a replication slot)

### DISCUSSION THREAD

**Discussion by abhishekmishragithub** [getdozer/dozer#1540] [Q&A] [answered]
With the following is the dozer configuration:

```
connections:
  - name: post_conn
    config: !Postgres
      user: ****
      password: ****
      host: localhost
      port: 5432
      database: postgres

sources:
  - name: dummy
    table_name:  yellow_taxi_trips
    connection: !Ref post_conn
    columns:

endpoints:
  - name: dummy
    path: /dummy
    table_name: yellow_taxi_trips

```

On running dozer, I am getting below error:

```
ERROR Failed to create a replication slot "dozer_slot_post_conn". Error: db error: ERROR: logical decoding requires wal_level >= logical
```
