### DISCUSSION TITLE
Onnx Feature - Loading Model from Object Storage

### DISCUSSION THREAD

**Discussion by chloeminkyung** [getdozer/dozer#1974] [General]
## Current Onnx Model Configuration Format

```yaml
udfs:
   - name: is_fraudulent
     config: !Onnx
       path: ./models/model_file
```

## Proposed New Format which is reusable

```yaml
udfs:
   - type: !Onnx
     name: is_fraudulent
     config: !LocalStorage
       details:
         path: data/zones/taxi_zone_lookup.csv

   - type: !Onnx
     name: is_fraudulent
     config: !S3Stroage
       details:
         # optional
         access_key_id: {{YOUR_ACCESS_KEY}}
         # optional
         secret_access_key: {{YOUR_SECRET_KEY}}
         region: {{YOUR_REGION}}
         bucket_name: {{YOUR_BUCKET_NAME}}
       path: ./models/model_file
```

### Original Object Storage Configuration Format

```yaml
  - config : !LocalStorage
      details:
        path: data
      tables:
        - !Table
          name: yellow_trips
          config: !Parquet
            path: yellow_trips
            extension: .parquet
    name: yellow_taxi
```

```yaml
  - config : !S3Storage
      details:
        access_key_id: {{YOUR_ACCESS_KEY}}
        secret_access_key: {{YOUR_SECRET_KEY}}
        region: {{YOUR_REGION}}
        bucket_name: {{YOUR_BUCKET_NAME}}
      tables:
        - !Table
          name: stocks
          config: !CSV
            path: .
            extension: .csv
    name: s3
```

**Comment by chubei** [comment]
1. I prefer if `access_key_id` and `secret_access_key` are not required, to make the use of public buckets easier.
2. I prefer option 1, but the enum name `S3Onnx` and `LocalOnnx` must be changed so this configuration format can be used in other places.
3. Option 2 is obviously not reusable, because `onnx` is embedded in the format.

**Comment by snork-alt** [comment]
I don't like this format. I would standardize the file loading across Dozer, whether is onnx or wasm and use URI formats. 

Also I would consider using https://github.com/apache/incubator-opendal or something similar so we can support any type of file storage at once.

**Reply by Xuanwo** [reply]
Thank you for mentioning OpenDAL! I'm one of the opendal committers. Please let me know if there is any assistance we can offer.

**Comment by chloeminkyung** [comment]
Utilizing opendal will consist of following steps:
1. logical changes
2. configuration format changes (optional)

list of supported object store services - https://github.com/apache/incubator-opendal/tree/main/core/src/services


Opendal uses its own `Result`
```rust
enum Result<T, E> {
   Ok(T),
   Err(E),
}
```

| opendal | require config changes | logical changes | dozer supported |
|---------|------------------------|-----------------|-----------------|
| s3      | optional               | supported       | y               |
| local   | required               |  supported               | y               |
| gcs     | required               | supported       | n               |
| azblob  | required               | supported       | n               |
| ..      |                        |                 |                 |

```rust
async fn read_data(op: Operator) -> Result<()> {
    let bs = op.read("test").await?;
    println!("data: {}", String::from_utf8_lossy(&bs));

    Ok(())
}
```

## S3
```rust
fn init() -> Result<Operator> {
    let mut builder = S3::default();
    builder.bucket("example");
    builder.access_key_id("access_key_id");
    builder.secret_access_key("secret_access_key");
    builder.region("us-east-1");

    let op = Operator::new(builder)?.finish();
    Ok(op)
}
```

config changes (optional)
```yaml
config: !S3Stroage
     details:
         # optional
         access_key_id: {{YOUR_ACCESS_KEY}}
         # optional
         secret_access_key: {{YOUR_SECRET_KEY}}
         region: {{YOUR_REGION}}
         bucket_name: {{YOUR_BUCKET_NAME}}
     path: ./models/model_file
```

## In-memory
```rust
fn init() -> Result<Operator> {
    let mut builder = Memory::default();
    builder.root("/tmp");

    let op: Operator = Operator::new(builder)?.finish();
    Ok(op)
}
```

config changes (optional)

```yaml
config: !LocalStorage
      details:
        path: data/zones/taxi_zone_lookup.csv
```
