### DISCUSSION TITLE
Yaml format

### DISCUSSION THREAD

**Discussion by v3g42** [getdozer/dozer#320] [Feature Requests]
This is a proposed structure of our YAML configuration. 

- Each YAML file represents one `application`. 
- Each `application` contains the following entities
   
### Connections 
Represents one unique connection to a data source. Eg: Postgres
### Sources 
Represents one source, typically a table in a database with a unique schema

   - Maps to a connection
   - Has one unique
   - Select columns optionally
### Endpoints 
Represents one api to be published. Both in REST and gRPC formats. 
   -  Each endpoint represents one API endpoint to be published
   - Has one `cache` object attached
   - Has one `SQL` transformation
   - Produces one output `schema`

### Sample
```
app_name: "Users"
api: 
  rest: 
    port: 8080
    url: [::0]
    cors: true # Permissive
  grpc: 
    port: 50051
    url: [::0]
    web: true # Enable web support to convert HTTP/1 to HTTP/2 
    cors: true
  
  auth: false # None / JWT security
  
  internal:
     port: 50052
     host: [::1]
  
connections:
  - name: users_db 
    db_type: Postgres
    authentication: !PostgresAuthentication
    user: postgres
    password: postgres
    host: localhost
    port: 5432
    database: users
sources:
  - name: users
    table_name: users
    connection: !ref users_db
    history_type: null
    refresh_config: RealTime
endpoints:
  - name: users
    path: /marketing/users
    sql: select id, email, phone from users;
    index:
     # Unique key is required for updates/deletes
      unique_key:
        - id 
```
