### ISSUE TITLE
Wild card in projection throws an error

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#1013]
### Wild card in projection
```
thread '<unnamed>' panicked at 'not supported yet', dozer-sql/src/pipeline/planner/projection.rs:50:40
```

### Config
```
app_name: first_app

# Define your connections here
connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: 127.0.0.1
      port: 5433
      database: pagila
    name: postgres_connection

# Each table is a source 
sources:
  - name: actor
    table_name: actor
    columns: []
    connection: !Ref postgres_connection
    refresh_config: null

sql: select * into actor_test from actor;
# Each of the endpoints are configured here
endpoints:
  - name: actor_test
    table_name: actor_test
    path: /api/actor_test
    index: null

```
