### ISSUE TITLE
String primary index doesnt work in path of API endpoint

### ISSUE THREAD

**Issue by karolisg** [getdozer/dozer#1085]
## Describe the bug
I have table, in which primary key is string. After sync, when I try to access it from API with URL `GET /{endpoint}/{primary_key}`, it gives error `Failed to parse the field: expected value at line 1 column 1`.

## Environment
- **Dozer version**: 0.1.19

## To Reproduce
It can reproduced with flights sample database https://github.com/getdozer/dozer-samples/tree/main/pg-flights

After success sync, run API and try access those urls

Full list - http://localhost:8080/airports_data
<img width="798" alt="Screenshot 2023-02-28 at 06 50 10" src="https://user-images.githubusercontent.com/1695346/221757079-5928c1f7-fb06-4061-bec1-37a3eb655c6b.png">

One airport - http://localhost:8080/airports_data/AAQ
<img width="798" alt="Screenshot 2023-02-28 at 06 50 28" src="https://user-images.githubusercontent.com/1695346/221757116-6b7029c6-22da-4117-af6f-2187f36de189.png">

1. Share your `dozer-config.yaml`
```
app_name: pg_airports
connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5437
      database: flights
      schema: public
    name: flights

sources:
  - name: airports
    table_name: airports_data
    columns:
    connection: !Ref flights

sql: |
  SELECT
    airport_code,
    airport_name
  INTO airports_data
  FROM airports;


endpoints:
  - name: airports_data
    path: /airports_data
    table_name: airports_data
    index:
      primary_key:
        - airport_code
```
