### ISSUE TITLE
Dozer silently quits when have no permission to write to home directory

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1345]
## Describe the bug
Dozer silently quits when have no permission to write to home directory

## Environment
- **Dozer version**: 0.1.14
- **OS Version**: MacOS
- **Docker Compose Version(Optional)**: 

## To Reproduce

1. Share your `dozer-config.yaml`

```yaml
app_name: dozer-ingest-users
connections:
  - config: !Grpc
      schemas: !Inline |
        {
          "users": {
            "schema": {
              "fields": [
                {
                  "name": "id",
                  "typ": "Int",
                  "nullable": false
                },
                {
                  "name": "name",
                  "typ": "String",
                  "nullable": true
                }
              ]
            }
          }
        }
    name: ingest

sources:
  - name: users
    table_name: users
    connection: !Ref ingest
    columns:

endpoints:
  - name: users
    path: /users
    table_name: users
    index:
      primary_key:
```

2. `sudo mkdir .dozer`
3. `dozer`

## Logs
```text
____   ___ __________ ____
|  _ \ / _ \__  / ____|  _ \
| | | | | | |/ /|  _| | |_) |
| |_| | |_| / /_| |___|  _ <
|____/ \___/____|_____|_| \_\


Dozer Version: 0.1.14
```
