### ISSUE TITLE
Dozer dramatically slows down after 7m records

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1370]
This is not due to the cache population because in the sample I was not running the cache. 
Seems due to something else.

## Config file:
```
cache_max_map_size: 7999987200
app_max_map_size: 7999987200

connections:
  - config : !LocalStorage
      details:
        path: /Users/matteo/dozer-ny-taxi/data
      tables:
        - !Table
          name: trips
          prefix: /trips
          file_type: parquet
          extension: .parquet
        - !Table
          name: zones
          prefix: /zones
          file_type: csv
          extension: .csv
    name: ny_taxi

sources:
  - name: zones
    table_name: zones
    connection: !Ref ny_taxi
    columns:
  - name: trips
    table_name: trips
    connection: !Ref ny_taxi
    columns:


sql: |
  SELECT trip_distance, PULocationID, DOLocationID, puz.Zone as pickup_location, doz.Zone as dropout_location
  INTO trips_cache
  FROM trips
  LEFT JOIN zones puz ON trips.PULocationID = puz.LocationID
  LEFT JOIN zones doz ON trips.DOLocationID = doz.LocationID;

commit_timeout: 500
commit_size: 50000

endpoints:
  - name: trips_cache
    path: /joined_trips
    table_name: trips_cache
```

## Run it with 
```
dozer app run 
```
