### ISSUE TITLE
GRPC query method doesnt work 

### ISSUE THREAD

**Issue by karolisg** [getdozer/dozer#1379]
## Describe the bug
If table contains any number, GRPC query method fails with error like `Response message parsing error: invalid wire type 7 at offset 217`

<img width="1120" alt="Screenshot 2023-04-04 at 16 08 52" src="https://user-images.githubusercontent.com/1695346/229801643-6b395393-fc15-4e60-a9c5-65ac98b4cc76.png">

This started to happen after `feat: u128 and i128 Field and FieldType (#1315)` (611912ee486d742773c5c43a515b4b3392bac6f4)

## Environment
- **Dozer version**: 0.1.15 (611912ee486d742773c5c43a515b4b3392bac6f4)

## To Reproduce

1. Share your `dozer-config.yaml`
```
app_name: flight-microservices
app_max_map_size: 737280

flags:
  grpc_web: true

api:
  api_security: !Jwt
    ABCD


connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: 0.0.0.0
      port: 5437
      database: flights
    name: flights_conn

#sql: |
#  select f.arrival_airport as airport, a.coordinates as coordinates, COUNT(t.ticket_no) as tickets
#  INTO airports_count
#  from tickets t
#  join ticket_flights tf on t.ticket_no = tf.ticket_no
#  join flights f on tf.flight_id = f.flight_id
#  join airports a on f.arrival_airport = a.airport_code
#  group by f.arrival_airport, a.coordinates;
#
#  select extract(HOUR FROM f.window_start) as start, count(f.window_start) as dep_count
#  INTO departures_count
#  from TUMBLE(flights, scheduled_departure, '4 HOURS') f
#  group by extract(HOUR FROM f.window_start)

sources:

  - name: tickets
    table_name: tickets
    columns:
    connection: !Ref flights_conn

  - name: flights
    table_name: flights
    columns:
    connection: !Ref flights_conn

  - name: ticket_flights
    table_name: ticket_flights
    columns:
    connection: !Ref flights_conn

  - name: airports
    table_name: airports
    columns:
    connection: !Ref flights_conn

endpoints:
  - name: flights
    path: /bookings/flights_x
    table_name: flights
    index:
      primary_key:
        - flight_id

  - name: airports
    path: /bookings/airports
    table_name: airports
    index:
      primary_key:
        - airport_code
```
3. Use pg-flights database with dozer
...
