### ISSUE TITLE
Secondary index configuration

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1445]
Example

```yaml
secondary: 
  skip_default_indexes: 
      - col_not_to_indexed
      - col_not_to_indexed2
  indexes:
    - type: sorted_inverted
      fields: ["open", "close"]
    - type: full_text
      field: "open"      
```
