### ISSUE TITLE
Handle quicknode's nonconformant jsonrpc response

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1455]
The primary problem is that `web3` will stuck when quicknode returns an error.

Root cause:

```json
{"jsonrpc":"2.0","id":2,"result":null,"error":{"code":-32602,"message":"eth_getLogs and eth_newFilter are limited to a 10,000 blocks range"}}
```

```rust
#[serde(deny_unknown_fields)]
```

**Comment by chubei** [comment]
The response from quicknode is against [jsonrpc spec](https://www.jsonrpc.org/specification#response_object).

Both [jsonrpc](https://github.com/paritytech/jsonrpc) and [jsonrpsee](https://github.com/paritytech/jsonrpsee) treat this as a deserialization error.

A possible solution:

1. Fork `jsonrpsee` and modify the deserialization code to allow `"result": null` in an error response. This should be a one-line change.
2. Copy code from `web3` and depend on `jsonrpsee` fork to write our own ethereum client. `jsonrpsee` already has the clients so it should be easy, we only need the type definitions from `web3`.

What do you think @v3g42 @karolisg?

Also can we contact quicknode customer service and ask them to fix this bug?

**Comment by chubei** [comment]
From QuickNode Support:  Our engineering team is working on this change. We will keep you posted on the progress.

**Comment by v3g42** [comment]
Great.

**Comment by chubei** [comment]
Confirmed the quicknode fix using following configuration file:

```yaml
app_name: working_app
connections:
  - config: !Ethereum
      provider: !Log
        filter:
          addresses: []
          topics: []
        wss_url: "{{ETH_WSS_URL}}"
    name: eth_logs
sql: |
  -- Eth stats table
  select block_number, sum(id) into eth_stats
  from eth_logs
  group by block_number;

  -- Eth block stats
  select block_number, id into eth_block_stats
  from eth_logs
  group by block_number, id;

sources:
  - name: eth_logs
    table_name: eth_logs
    columns:
      - block_number
      - id
    connection: !Ref eth_logs
endpoints:
  - id: 1b44cca2-7631-4f0c-8b6e-254c08d28dae
    name: eth_stats
    table_name: eth_stats
    path: /eth/stats
    index:
      primary_key:
        - block_number
  - name: eth_logs
    path: /eth/logs
    table_name: eth_block_stats
    index:
      primary_key:
        - block_number
        - id
```

This is just the `eth-logs` e2e test with `from_block` and `to_block` removed.
