### ISSUE TITLE
[Docs] Add a reference to the requisites of using PostgreSQL connectors

### ISSUE THREAD

**Issue by abhishekmishragithub** [getdozer/dozer#1543]
**Describe the documentation issue**

Lack of reference to the requisites of using PostgreSQL connectors with Dozer. The PostgreSQL recommended configuration is not mentioned in the doc or connector doc.

**Suggested improvement or correction**
- Add a reference to the requisites of using PostgreSQL connectors (The replication and WAL level config)

**Additional context**
Due to the lack of proper PostgreSQL config of WAL and other replication configs. Dozer throws the following error if you run it with a PostgreSQL connector.
Error: `ERROR Failed to create a replication slot "dozer_slot_post_conn". Error: db error: ERROR: logical decoding requires wal_level >= logical`

**Your environment (optional)**
Run the dozer on the local machine PostgreSQL with the following config:

```yaml
connections:
  - name: post_conn
    config: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5432
      database: postgres

sources:
  - name: dummy
    table_name:  yellow_taxi_trips
    connection: !Ref post_conn
    columns:

endpoints:
  - name: dummy
    path: /dummy
    table_name: yellow_taxi_trips

```

**Ongoing discussion**

- https://github.com/getdozer/dozer/discussions/1540

**Checklist**
Please ensure you have completed the following before submitting your issue:

- [x] I have searched the existing issues to make sure my issue hasn't already been reported.
- [x] I have provided a clear and concise description of the issue.
- [x] I have provided any relevant examples or references to support my suggestion.
- [x] I have filled out all sections of the issue template to the best of my ability.
