### ISSUE TITLE
PostgreSQL connector is not reading public schema by default, and throwing error `Table not found in any of the connections`

### ISSUE THREAD

**Issue by abhishekmishragithub** [getdozer/dozer#1548]
## Describe the bug
When using the PostgreSQL connector with Dozer, it does not read tables from the public schema by default. It throws an error `Table not found in any of the connections` when trying to access tables within the public schema. However, when explicitly adding the schema name in front of the table name, it works as expected.

## Environment
- **Dozer version**: 0.1.20
- **OS Version**: macOS Ventura 13.2.1 (silicon M1)
- **Docker Compose Version(Optional)**:  NA

## To Reproduce
-  Start a PostgreSQL by running:
```bash
brew services start postgresql@15
```
- Create a `users` table with few fields under `public` schema in PostgreSQL
- Use the following Dozer configuration and save it to `dozer-config.yaml` file

```yaml
  
connections:
  - name: post_conn
    config: !Postgres
      user: abhishekmishra
      password: ******
      host: localhost
      port: 5432
      database: postgres

sources:
  - name: dummy
    table_name:  users
    connection: !Ref post_conn
    columns:

endpoints:
  - name: users
    path: /users
    table_name: users
 
```
- Run `dozer -c dozer-config.yaml`

## Logs

```
2023-05-08T12:49:25.127237Z ERROR Table users not found in any of the connections    
2023-05-08T12:49:25.128150Z ERROR Source validation failed
```

## Workaround
Adding the schema name in front of the table name, like `public.users`, resolves the issue.

## Expected behavior
The PostgreSQL connector should read tables from the public schema by default. If no schema is mentioned, the public schema should be readable by default.

## Additional info 
- Following is the screenshot of the schema showing tables under the `public` schema.
![image](https://github.com/getdozer/dozer/assets/38150419/a81faac9-5a97-4dcf-90db-ab971095f454)

## Question
Is there anything I am missing? I just want to make sure that this is not intended behavior. The intended behavior should be that the PostgreSQL connector reads tables from the public schema by default if no schema is mentioned.
