### ISSUE TITLE
Order by does not work correctly if the response has decimal values

### ISSUE THREAD

**Issue by supergi0** [getdozer/dozer#1979]
## To Reproduce

1. Use the config file.
```
version: 1
app_name: quick-start-app
home_dir: ./.dozer
cache_dir: ./.dozer/cache

connections:
  - config: !Snowflake
      server: ""
      port: 443
      user: ""
      password: ""
      database: "GITHUB_SAMPLE_DATA"
      schema: PUBLIC
      warehouse: "COMPUTE_WH"
      driver: "SnowflakeDSIIDriver"
      role: "ACCOUNTADMIN"
    name: sn_data
   
sources:
 - name: sc1
   connection: sn_data
   table_name: STARS
   
 - name: sc2
   connection: sn_data
   table_name: GITHUB_REPOS_TOP
   
sql: |
 
 SELECT b.REPO_ID, b.REPO_NAME, AVG(a.COUNT) AS AVG_COUNT
 INTO tb1
 FROM sc1 a JOIN sc2 b ON a.REPO_ID = b.REPO_ID
 GROUP BY b.REPO_ID, b.REPO_NAME;

endpoints:
 - name: endpt1
   path: /endpt1
   table_name: tb1
```
2. Query the output at the endpoints by
```
{
    "$order_by": {"AVG_COUNT" : "desc"}
}
```
Attaching the query results as well.
[desc.txt](https://github.com/getdozer/dozer/files/12521169/desc.txt)
[asc.txt](https://github.com/getdozer/dozer/files/12521170/asc.txt)
