### ISSUE TITLE
Postgres connector field reordering works in schema but not in record

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2149]
Found a problem in postgres connector. Looks like the field reordering is not implemented. Can be reproduced using the postgres connector sample data with following config

```yaml
version: 1
app_name: simple-pg-sample
connections:
  - name: pagila_conn
    config: !Postgres
      user: postgres
      password: postgres
      host: 0.0.0.0
      port: 5433
      database: pagila

sources:
  - name: film
    connection: pagila_conn
    table_name: film
    columns:
      - title
      - film_id

endpoints:
  - name: film
    path: /film
    table_name: film
```

The type of `title` is `string`, `film_id` is `int`. While the schema is correct, the record is `[int, string]`
