### ISSUE TITLE
Incorrect `OnEvent` result after JOINs

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2150]
- Using postgres sample data and following configuration file:

```yaml
version: 1
app_name: quick-start-app
home_dir: ./.dozer
cache_dir: ./.dozer/cache
connections:
- config: !Postgres
    host: localhost
    port: 5433
    user: postgres
    password: postgres
    database: pagila
  name: postgres

sql:
  SELECT
    customer.customer_id,
    film.title
  INTO joined_rental
  FROM rental
  INNER JOIN customer ON rental.customer_id = customer.customer_id
  INNER JOIN inventory ON rental.inventory_id = inventory.inventory_id
  INNER JOIN film ON inventory.film_id = film.film_id;

endpoints:
- name: joined_rental
  table_name: joined_rental
  path: /joined_rental
```

- Run dozer until all data is ingested

- Call `dozer.generated.joined_rental.JoinedRentals/OnEvent` with empty message

- Use `psql -U postgres -h localhost -p 5433 -d pagila;` to connect to the postgres

- Run `update customer set first_name = 'alice' where customer_id = 1;`

# Expected Behaviour

`OnEvent` receives `DELETE` (typ: 1) and `INSERT` (typ: 0) events

# Actual Behaviour

`OnEvent` only receives `DELETE` (typ: 1) events
