### ISSUE TITLE
`dozer.lock` is not stable when there are multiple connections

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2152]
```
version: 1
app_name: quick-start-app
home_dir: ./.dozer
cache_dir: ./.dozer/cache
connections:
- config: !Postgres
    user: postgres
    password: "{{ BDW_DEMO_POSTGRES_PASSWORD }}"
    host: "{{ BDW_DEMO_POSTGRES_HOST }}"
    port: 5432
    database: pagila
  name: postgres
- config: !S3Storage
    details:
      region: ap-southeast-1
      bucket_name: dozer-samples
      access_key_id: '{{ BDW_DEMO_S3_ACCESS_KEY_ID }}'
      secret_access_key: '{{ BDW_DEMO_S3_SECRET_ACCESS_KEY }}'
    tables:
    - name: inventory
      config: !CSV
        path: pagila
        extension: .csv
  name: s3

sources:
- name: s3_inventory
  connection: s3
  table_name: inventory

sql:
  SELECT
    rental.rental_id,
    CONCAT(customer.first_name, ' ', customer.last_name) AS customer,
    film.title
  INTO joined_rental
  FROM rental
  INNER JOIN customer ON rental.customer_id = customer.customer_id
  INNER JOIN s3_inventory ON rental.inventory_id = inventory.inventory_id
  INNER JOIN film ON inventory.film_id = film.film_id;

endpoints:
- name: actor
  table_name: actor
  path: /actor

- name: inventory
  table_name: s3_inventory
  path: /inventory

- name: joined_rental
  table_name: joined_rental
  path: /joined_rental
```

Using above configuration file, run `dozer build --locked`,  there's possibility that dozer reports `dozer.lock is out of date`.

Seems only happen when there are multiple connections.

Contact @chubei for credentials used in this config.
