### ISSUE TITLE
Postgres ingestion performance test

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2293]
- We need a big enough dataset for snapshotting throughput test, ideally ~10G.
- We need some script to do inserts, updates and deletes to Postgres to test streaming throughput and latency.

**Comment by chubei** [comment]
Dataset:
https://getdozer.slack.com/archives/C03NW8QSA4Q/p1704364475602159?thread_ts=1704359758.003269&cid=C03NW8QSA4Q

Config:
https://getdozer.slack.com/archives/C03NW8QSA4Q/p1704364528228249?thread_ts=1704359758.003269&cid=C03NW8QSA4Q

Result:
- Snapshot: https://docs.google.com/spreadsheets/d/1B83HEUZKc3NHtA_QVEotbD5l0DRVu2nYtLOdsfFzuMw/edit#gid=1467169753
- Replication: Roughly ingestion throughput rate is around 50/55k/s operations. Avg latency for first operation to be ingested is 30-50ms.

**Comment by karolisg** [comment]
SQL for inserting some data for CDC testing

```
CREATE TABLE IF NOT EXISTS miner_data_stream(
 time TIMESTAMPTZ NOT NULL,
 miner_name VARCHAR(20),
 fan_percentage FLOAT,
 inserted_at timestamp
);

INSERT INTO miner_data_stream(
   miner_name,
   time,
   fan_percentage,
                              inserted_at)
SELECT
   name,
   HOURLY,
   abs(intensity - rval)*100 as fan,
   now()
FROM(
   SELECT
      miners.name,
      HOURLY,
      date_part('hour', HOURLY) _hour,
      random()*0.2 as rval
   FROM generate_series(
      '2029-1-14',
      '2029-12-14',
      INTERVAL '5 second'
   ) HOURLY
CROSS JOIN(
   SELECT DISTINCT(name)
   FROM miners)
miners
   LIMIT 100000
   ) m
INNER JOIN hours h ON date_part('hour', HOURLY) = h.hour
ORDER BY hourly;

TRUNCATE miner_data_stream;
```

Dozer config 
```
app_name: dozer-pg-sample
version: 1
connections:
  - name: dozer_pg_db
    config: !Postgres
      user: postgres
      password: postgres
      host: localhost
      port: 5433
      database: bank_db

flags:
  enable_app_checkpoints: true

sources:
  - name: miner_data_stream
    table_name: miner_data_stream
    connection: dozer_pg_db

  - name: miners
    table_name: miners
    connection: dozer_pg_db

endpoints:
  - name: miner_data_stream
    path: /miner_data_stream
    table_name: miner_data_stream

  - name: miners
    path: /miners
    table_name: miners
```
