### ISSUE TITLE
Performance comparison of movement tools

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#2310]
https://link.excalidraw.com/l/9s77uqbZtdz/3sMTt60DYfb
https://docs.google.com/spreadsheets/d/1y7twmziEWOD2RKxi7ejd7zIcEXy9h62xEiOWRQVrSFI/edit#gid=0
https://hackmd.io/@eS6hbT4DQXupxPVYXcMjjw/rJxERd48Fp

**Comment by chubei** [comment]
Data generation

`pgbench -i -s 5000 -F 20 bench_2`

Kafka tar.gz
https://kafka.apache.org/downloads

Install connector
https://debezium.io/documentation/reference/2.5/connectors/postgresql.html

After installing connector add path to `kafka_2.13-3.6.1/config/connect-standalone.properties`
Example `plugin.path=/home/ec2-user/kafka_2.13-3.6.1/plugins`

Config for pg connector
kafka_2.13-3.6.1/config/pg-test-connector.properties
```
name=pg-test-connector-perf
connector.class=io.debezium.connector.postgresql.PostgresConnector
tasks.max=1
plugin.name=wal2json
database.hostname=localhost
database.port=5432
database.user=postgres
database.password=postgres
database.dbname =bench_2
database.server.name=DozerTestServer
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
table.include.list=public.pgbench_accounts
table.exclude.list=public.pgbench_tellers
snapshot.lock.timeout.ms=10000
#signal.data.collection=public.dbz_signal
#snapshot.include.collection.list=public.pgbench_accounts
#snapshot.select.statement.overrides=public.pgbench_accounts
offset.storage.file.filename=pg_offset
bootstrap.servers=localhost:9092
#snapshot.select.statement.overrides.public.pgbench_accounts=SELECT * FROM pgbench_accounts LIMIT 100
```

1. Start zookeeper `bin/zookeeper-server-start.sh config/zookeeper.properties`
2. Start kafka `bin/kafka-server-start.sh config/server.properties`
3. Start connect + pg `bin/connect-standalone.sh config/connect-standalone.properties config/pg-test-connector.properties`

**Comment by chubei** [comment]
```yaml
app_name: dozer-pg-sample
version: 1
connections:
  - name: dozer_pg_db
    config: !Postgres
      user: chubei
      password: postgres
      host: localhost
      port: 5432
      database: bench_2

endpoints:
  - table_name: pgbench_accounts
    kind: !Dummy
```

```text
Snapshotting for connection dozer_pg_db took 17.221954542s
```

**Comment by chubei** [comment]
`aerospike.conf`:

```
# Aerospike database developer configuration file.

service {
    run-as-daemon false
    cluster-name cakery
}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3000
    }

    heartbeat {
        mode multicast
        multicast-group 239.1.99.222
        port 9918

        # To use unicast-mesh heartbeats, remove the 3 lines above, and see
        # aerospike_mesh.conf for alternative.

        interval 150
        timeout 10
    }

    fabric {
        port 3001
    }

#   info {
#       port 3003
#   }
}

namespace test {
    replication-factor 1

    storage-engine memory {
        data-size 16G
    }
}
```

Run aerospike:

```bash
docker run --name aerospike -p 3000-3002:3000-3002 -v ./aerospike.conf:/aerospike.conf aerospike/aerospike-server-enterprise --config-file /aerospike.conf
```

Run dozer:

```yaml
app_name: dozer-bench
version: 1
connections:
  - name: pgbench
    config: !Postgres
      user: chubei
      password: postgres
      host: localhost
      port: 5432
      database: bench

endpoints:
  - table_name: pgbench_accounts
    kind: !Aerospike
      namespace: test
      hosts: localhost
      set_name: test
```

23s, 592 MB/s
