### ISSUE TITLE
ReplicationType changes broke connector ls and empty columns support

### ISSUE THREAD

**Issue by v3g42** [getdozer/dozer#707]
## Describe the bug
- [ ] `connector ls` doesnt work
- [ ] Cannot start `dozer` with empty columns

## Environment
Local

## To Reproduce
```
app_name: pagila-example
connections:
  - db_type: Postgres
    authentication: !Postgres
      user: postgres
      password: postgres
      host: 0.0.0.0
      port: 5433
      database: pagila
    name: pagila

sources:
  - name: film
    table_name: film
    connection: !Ref pagila

endpoints:
  - name: films
    path: /films
    enable_rest: false
    enable_grpc: true
    sql: select film_id, title from film;
    index:
      primary_key:
        - film_id
```
- Cannot send empty colulms
- Even if columns are available, connector ls doesnt work

...
N. Share you error
```
 cargo run --bin dozer connector ls
    Finished dev [unoptimized + debuginfo] target(s) in 0.68s
     Running `target/debug/dozer connector ls`
2023-01-22T11:20:16.720730Z ERROR Invalid column type
```
cargo run --bin dozer
    Finished dev [unoptimized + debuginfo] target(s) in 0.52s
     Running `target/debug/dozer`

[pagila] ⠁ Validating connection to source                                                           ░░░░░░░░░░░░░░░░░░░░2023-01-22T11:20:48.930552Z  INFO Starting Rest Api Server on http://0.0.0.0:8080 with security: None
2023-01-22T11:20:48.931441Z  INFO Starting 10 workers
2023-01-22T11:20:48.931525Z  INFO Starting gRPC server on http://0.0.0.0:50051 with security: None
2023-01-22T11:20:48.931710Z  INFO Tokio runtime found; starting in existing Tokio runtime
2023-01-22T11:20:49.091429Z  INFO [pagila] ✓ Connection validation completed
2023-01-22T11:20:50.249650Z  WARN Internal Pipeline server - message reveived error: RecvError
2023-01-22T11:20:50.250101Z ERROR Replication type not found
```
