### ISSUE TITLE
Snowflake sample bincode error

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#756]
## Describe the bug
Snowflake sample reports bincode error on REST query.

## Environment
- **Dozer version**: main
- **OS Version**: macOS 13.1
- **Docker Compose Version(Optional)**: 

## To Reproduce

1. Share your `dozer-config.yaml`

```yaml
app_name: snowflake-tutorial
connections:
  - db_type: Snowflake
    authentication: !Snowflake
      server: jkjmmwd-sy09852.snowflakecomputing.com
      port: 443
      user: dozer
      password: <your_password_here>
      database: DOZER_SAMPLE_DATA
      schema: PUBLIC
      warehouse: COMPUTE_WH
      driver: "{/opt/snowflake/snowflakeodbc/lib/libSnowflake.dylib}"
    name: sn_data
sources:
  - name: ORDERS_BEI
    connection: !Ref sn_data
    table_name: ORDERS_BEI
    columns:
endpoints:
  - name: ORDERS_BEI
    path: /orders
    index:
      primary_key:
        - O_ORDERKEY
```

2. Run cli command `dozer`
3. Visit http://localhost:8080/orders
4. Failed to parse the field: Bincode does not support the serde::Deserializer::deserialize_any method

## Expected behavior
Query should work

## Logs
If applicable, add logs to help explain your problem.
