### ISSUE TITLE
Confusing error message when connection configuration format is wrong

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#954]
## Describe the bug
When I put a wrong ethereum connector config in `dozer-config.yaml`, it's deserialized as postgres connector and validation fails reporting postgres validation error.

## Environment
- **Dozer version**: main
- **OS Version**: MacOS
- **Docker Compose Version(Optional)**: 

## To Reproduce

1. Share your `dozer-config.yaml`

```yaml
app_name: working_app
connections:
  - authentication: !Ethereum
      filter:
        from_block: 0
        to_block: 1
        addresses: []
        topics: []
      wss_url: "{{ETH_WSS_URL}}"
      name: eth_logs
    db_type: Ethereum
    name: eth_logs
sql: |
  -- Eth stats table
  select block_number, sum(id) into eth_stats
  from eth_logs
  group by block_number;
  -- Eth block stats
  select block_number, id into eth_block_stats
  from eth_logs
  group by block_number, id;
sources:
  - name: eth_logs
    table_name: eth_logs
    columns:
      - block_number
      - id
    connection: !Ref eth_logs
endpoints:
  - id: 1b44cca2-7631-4f0c-8b6e-254c08d28dae
    name: eth_stats
    table_name: eth_stats
    path: /eth/stats
    index:
      primary_key:
        - block_number
  - name: eth_logs
    path: /eth/logs
    table_name: eth_block_stats
    index:
      primary_key:
        - block_number
        - id

flags:
  dynamic: false
```

2. Run cli command `dozer init`
3. Share you error

```text
2023-02-21T01:02:55.016241Z ERROR [eth_logs] X Connection validation error: Failed to connect to postgres with the specified configuration. error connecting to server: failed to lookup address information: nodename nor servname provided, or not known    
2023-02-21T01:02:55.016511Z ERROR Source validation failed    
```

## Expected behavior
Dozer should report deserialization error.

## Logs
If applicable, add logs to help explain your problem.
